name: Browser
on: [push]

jobs:
  dusk-php:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup
        run: |
          cd code
          cp .env.dusk.remote .env
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE gasdottong_test character set UTF8mb4 collate utf8mb4_bin;"
          composer install --no-interaction --no-progress --prefer-dist
          php artisan key:generate
          php artisan migrate
          php artisan db:seed
          php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
          ./vendor/laravel/dusk/bin/chromedriver-linux &
          php artisan serve --no-reload &

      - name: running tests
        env:
          APP_URL: "http://127.0.0.1:8000"
        run: |
          cd code
          php artisan dusk
