name: Tests
on: [push]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cd code
    - uses: nathanheffley/laravel-phpunit-action@master
